### ISSUE TITLE
overlapping prime ministers

### ISSUE THREAD

**Issue by pmur002** [dakvid/dakvid.github.io#1]
Something seems wrong - unless Nash and Holyoake shared power at the same time ?

**Comment by dakvid** [comment]
Doh! Good spotting, thanks for pointing that out. I missed it when I first played around with this many months ago, and didn't look closely enough when I came back to it recently, trusting past me too much.

Holyoake became Prime Minister for 2-3 months before the 1957 election, which Nash one. Then Holyoake won the 1960 election (and several more). I didn't realise we'd had a repeat Prime Minister post-war, so nice to learn something new.

**Comment by dakvid** [comment]
Graphic updated, with a note in the post. Thanks Paul!
